version: "3.1"
services:
  guduo:
    build:
      context: ""
    image: centos:guduo
    restart: always
    tty: true
    volumes:
      - ./:/guduo
    networks:
      - guduo
    container_name: guduo

networks:
  guduo:
    driver: bridge
